EllokartAdmin/Models/Payment/Payment.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace EllokartAdmin.Models.Payment
{
    public class Payment
    {
        public string MobileNo { get; set; }
        public string MembershipPlan { get; set; }
    }
}

EllokartAdmin/Models/Payment/PaymentCode.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace EllokartAdmin.Models.Payment
{
    public class PaymentCode
    {
        public string MobileNo { get; set; }
        public long PlanId { get; set; }
        public string MembershipPlan { get; set; }
    }
}

EllokartAdmin/Controllers/PaymentController.cs
using EllokartAdmin.Models;
using EllokartAdmin.Models.Payment;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Web;
using System.Web.Mvc;

namespace EllokartAdmin.Controllers
{
    public class PaymentController : Controller
    {
        // GET: Payment
        ForDb db = new ForDb();
        public static string Baseurl = ForDb.BaseURL;
        private string GetMembershipPlan = Baseurl + "MembershipPlan/AllMembershipPlans";
        private string GeneratePaymentCodeUrl = Baseurl + "Franchise/GeneratePaymentCode";
        APIResult oResult = null;
        // GET: Payment
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult GeneratePaymentCode()
        {
            //String Id=null;
            string sUrl = GetMembershipPlan;
            Payment _payment = new Payment();
            //_payment.MobileNumber = Id;

            oResult = new APIResult();
            HttpClient client = new HttpClient();
            string token = string.Empty;
            client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Basic", token);
            HttpResponseMessage response = client.PostAsJsonAsync(sUrl, _payment).Result;
            response.EnsureSuccessStatusCode();
            var data = response.Content.ReadAsAsync<APIResult>().Result;
            var details = data.sResult;
            if (data.sMessage == "Successfully collected all membership plans ")
            {

                ViewBag.message = data.sResult;
            }

            return View();
        }
        public ActionResult PaymentCodeGenearate(long MembershipPlanId, string MobileNumber)
        {
            //String Id=null;
            string sUrl = GeneratePaymentCodeUrl;
            PaymentCode _payment = new PaymentCode();
            _payment.MobileNo = MobileNumber;
            _payment.PlanId = MembershipPlanId;

            oResult = new APIResult();
            HttpClient client = new HttpClient();
            string token = string.Empty;
            client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Basic", token);
            HttpResponseMessage response = client.PostAsJsonAsync(sUrl, _payment).Result;
            response.EnsureSuccessStatusCode();
            var data = response.Content.ReadAsAsync<APIResult>().Result;
            var details = data.sResult;
            if (data.sMessage == "Success")
            {               
                ViewBag.message = data.sResult;
                return View();
            }
            else
            {
                ViewBag.message = data.sMessage;
                return View();
            }
            
            
        }
    }
}

EllokartAdmin/Views/Payment/GeneratePaymentCode.cshtml
@model EllokartAdmin.Models.Payment.Payment
@{
    ViewBag.Title = "GeneratePaymentCode";
    Layout = "~/Views/Shared/_LayoutPage1.cshtml";
}


@{
    var data = ViewBag.message;
    var data1 = ViewBag.Validation;
    var d1 = data[0].MembershipPlan;
    var d2 = data[0].MembershipPlanId;
   
}

@using (Html.BeginForm("PaymentCodeGenearate", "Payment", FormMethod.Post))
{
    <div class="right_col" role="main">
        <div class="">
            <div class="page-title">
                <div class="title_left">
                </div>
            </div>
            <div class="clearfix"></div>

            <div class="row">

                <div class="col-md-12 col-sm-12 col-xs-12">
                    <div class="x_panel" style="margin-left:300px">
                        <div class="x_title">
                            <br />
                            <h4 class="card-title">Generate Payment Code</h4>
                            <div class="clearfix"></div>
                        </div>
                        <div style="height: 50px">
                          
                            <label for="position-bottom-left">Membership Plan </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <select  class="form-control" name="MembershipPlanId">
                                    <option value="@data[0].MembershipPlanId" selected>--Select--</option>
                                    @foreach (var item in data)
                                    {
                                        <option value="@item.MembershipPlanId" >@item.MembershipPlan</option>
                                    }
                                </select>
                            </div>
                        </div>
                        <br />
                        <div class="form-group">
                            <label for="position-bottom-left">Mobile Number</label>
                            <div class="col-md-6 col-sm-6 col-xs-12">

                                <input type="text" id="MobileNumber" name="MobileNumber" required="required" class=" form-control" />
                            </div>
                        </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-success" id="btnsubmit">Generate</button>
                            @*<a class="btn btn-primary" href="@Url.Action("PaymentCodeGenearate", "Home")">
                                Cancel*@
                            @*</a>*@
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
}

EllokartAdmin/Views/Payment/PaymentCodeGenearate.cshtml
@{
    ViewBag.Title = "PaymentCodeGenearate";
    Layout = "~/Views/Shared/_LayoutPage1.cshtml";
}
@{ 
    var data = ViewBag.message;
}
<div class="right_col" role="main">
    <div class="">
        <div class="page-title">
            <div class="title_left">
            </div>
        </div>
        <div class="clearfix"></div>

        <div class="row">

            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel" style="margin-left:300px">
                    <div class="x_title">
                        <br />
                        <h4 class="card-title">Generate Payment Code</h4>
                        <div class="clearfix"></div>
                    </div>
                   <div>
                       <input type="text" id="Sellercode" value="@data[0].SellerRefId" readonly/>
                   </div>
                </div>
            </div>
        </div>
    </div>

</div>